import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';

import 'screens/splash_screen.dart';
import 'firebase_options.dart'; // This file will be generated by flutterfire configure

import 'theme/app_theme.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  
  await dotenv.load();

  // NOTE: You must run 'flutterfire configure' to generate firebase_options.dart
  // For now, we wrap in a try-catch to allow the UI to run even if not configured yet (for demo/check)
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
  } catch (e) {
    debugPrint("Firebase not initialized: $e");
    // In a real app, you might show an error screen or use a mock service
  }

  runApp(const ParaGoApp());
}

class ParaGoApp extends StatelessWidget {
  const ParaGoApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'ParaGo',
      debugShowCheckedModeBanner: false,
      theme: AppTheme.lightTheme,
      home: const SplashScreen(),
    );
  }
}
